# File generated by the BNF Converter (bnfc 2.9.5).

from setuptools import setup, find_packages
setup(name = 'pygment-syntax', version = 0.1,
      packages = ['syntax'],
      entry_points = {'pygments.lexers':"syntax=syntax:SyntaxLexer"},
      install_requires = ['pygments'])
