-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language Syntax.

module Language.Lambda.Syntax.Abs where

import Prelude (String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Program = AProgram [Command]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Command = CommandCompute Term
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Term
    = Var VarIdent
    | Lam Pattern ScopedTerm
    | App Term Term
    | Paren Term
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ScopedTerm = AScopedTerm Term
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Pattern = APattern VarIdent
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype VarIdent = VarIdent String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

