# File generated by the BNF Converter (bnfc 2.9.5).

import pygments.lexer
from pygments.token import *
__all__ = ["SyntaxLexer"]
class SyntaxLexer(pygments.lexer.RegexLexer):
    name = 'Syntax'
    aliases = ['syntax']
    KEYWORDS = ['compute', 'λ']
    def get_tokens_unprocessed(self, text):
        for index, token, value in super(SyntaxLexer,self).get_tokens_unprocessed(text):
            if token is Name and value in self.KEYWORDS:
                yield index, Keyword, value
            else:
                yield index, token, value
    tokens = {
        'root': [
            (r'--.*\n', Comment),
            (r'[a-z]([\'_]|\d|[a-zA-Z])*', Name),
            (r'[A-Z]([\'_]|\d|[a-zA-Z])*', Name),
            (r'[a-zA-Z]([a-zA-Z]|\d|_|\')*', Name),
            (r';|:|\.|\[|\]|\(|\)|,|↦|∀|=|->', Operator),
            (r'(\d)+', Number.Integer),
            (r'(\d)+\.(\d)+(e(-)?(\d)+)?', Number.Float),
            (r'"((.)(?<!["\\])|\\["\\nt])*"', String.Double),
            (r'\'((.)(?<![\'\\])|\\[\'\\nt])\'', String.Char),
            (r'\s+', Token.Space)
        ]
    }
